package de.lathspell.dtx2gp.frontend;

import java.io.IOException;
import java.util.Properties;

public class Version {

    /** Get pom.xml version string that was generated by Maven. */
    public static String getVersion() {
        Properties properties = new Properties() ;
        try {
            properties.load(Version.class.getResourceAsStream("/dtx2gp.properties"));
            return properties.getProperty("dtx2gp.version");
        } catch (IOException e) {
            return "NULL";
        }
    }

}
